apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-depl
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: myapp-container
        image: nginx
  replicas: 2
  selector:
    matchLabels:
      type: front-end