apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers:
  - name: myapp-container
    image: nginx
    ports:
    - containerPort: 8080
  resources:
    requests:
      memory: "4Gi"
      cpu: 2
